# This code-annotations configuration file supports openedx-events

source_path: ./
report_path: reports
safelist_path: .annotation_safe_list.yml
coverage_target: 100.0
annotations:
  feature_toggle:
    # See annotation format documentation: https://docs.openedx.org/projects/openedx-events/en/latest/reference/in-line-code-annotations-for-an-event.html
    - ".. event_type:":
    - ".. event_name:":
    - ".. event_description:":
    - ".. event_data:":
    - ".. event_key_field:":
    - ".. event_warning:":
extensions:
    python:
        - py
rst_template: doc.rst.j2
